### ISSUE TITLE
The "Save All" button for attachments does only save multiple copies of winmail.dat under decoded attachment names

### ISSUE THREAD

**Issue by andras63** [dugite-code/LookOut-fix-version#13]
## Context

The "Save All" button for attachments does only save multiple copies of winmail.dat under decoded attachment names

* Operating System:
* Thunderbird version number: 60
* 64 bit/32 bit:
* LookOut (fix version) version number:

# Expected Behavior

Save all exports decoded files to selected file location

# Current Behavior

Files are exported with correct file names but without decoding. Files appear to be identical to to main winmail.dat file

**Comment by andras63** [comment]
Happens on company account, so I can't post sample data. Will try to reproduce with postable data.

**Comment by dugite-code** [comment]
@andras63 could you try the [1.2.2 Beta 2](https://github.com/dugite-code/LookOut-fix-version/releases/tag/v1.2.22b2) on the release page. This also has the debugging check box added in the settings.

You can then view the debug log in the error console

![image](https://user-images.githubusercontent.com/12742064/44315467-0b178180-a457-11e8-88e0-5728cdb3fda1.png)

**Comment by dugite-code** [comment]
The beta previously linked is now live on the Thunderbird add-on site. Let me know if you're still having issues.

**Comment by andras63** [comment]
I finally had time to test and can confirm that 1.2.22 behaves as expected.
