### ISSUE TITLE
Selecting mails with .dat will make TB 60.0.B10 unusable

### ISSUE THREAD

**Issue by petesky** [dugite-code/LookOut-fix-version#14]
As written in topic - had no problems until latest TB beta. Every time i select the mail with .DAT attachment (preview will open when selecting the mail) TB will become unusable; have to terminate the process.

**Comment by dugite-code** [comment]
I've just tested TB60 Beta 10 on my Debian VM (Plan to test on windows 10 when I have some free time) and have been unable to re-produce your error. I'll try to help but please be away my main target is the stable release channel Thunderbird

Could you try the [1.2.2 Beta 2](https://github.com/dugite-code/LookOut-fix-version/releases/tag/v1.2.22b2) available on the release page. This also has the debugging check box added in the settings. Also: 

* What operating system are you currently on?
* Is this 32bit Thunderbird or 64 bit?
* Is this a true win.dat email? e.g. if you click `More -> View source` do you find `Content-Type: application/ms-tnef; name="winmail.dat"` just above the attachment blob?
* Is it only one email that causes the hang or is it multiple emails?

After debugging is enabled you can then view the debug log in the error console

![image](https://user-images.githubusercontent.com/12742064/44315467-0b178180-a457-11e8-88e0-5728cdb3fda1.png)

**Comment by petesky** [comment]
I'm on W10 1803 x86 so its TB x86 and it is a mail with just one winmail.dat attachment. Only this mail causes the error. Whenever i cklick on the mail it hangs with "Loading message ..." in status bar after which TB window will become light gray (no response message) also with current beta.

Part of source (edited for privacy reason) :
```
MIME-Version: 1.0

--_000_000000000000000000000000000000000000000000000000xxxinte_
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

--_000_000000000000000000000000000000000000000000000000xxxinte_
Content-Disposition: attachment; filename="winmail.dat"
Content-Transfer-Encoding: base64
Content-Type: application/ms-tnef; name="winmail.dat"
```

**Comment by dugite-code** [comment]
The TNEF parser is quite old so could be an edge case.

One more suggestion is to do a folder repair, Right click the folder the mail is located select Properties then click the repair folder button. This will force a reload of the mail from the IMAP server, just in case it didn't download correctly.

![image](https://user-images.githubusercontent.com/12742064/44383063-fc5dc700-a549-11e8-94b4-9e353414020e.png)

**Comment by petesky** [comment]
Inbox is POP and it happens also when i move the mail to a local backup folder. The mail itself is not very large (only 10KB or so) but it seems it will only happen when there is just one winmail,dat as attachment. If there are more (a winmail.dat and other attachmetns) it will open the mail normally. I cannot debug as TB is crashing whenver i click on the mail.
