### ISSUE TITLE
ATN hu

### ISSUE THREAD

**Issue by ovari** [dugite-code/LookOut-fix-version#23]
Please update the [ATN hu locale](https://addons.thunderbird.net/hu/thunderbird/addon/lookout-fix-version/)

1. Title:
LookOut (fix version)
→
MutasdMeg! (LookOut)

2. Summary:
LookOut is a plugin which allows Thunderbird to interface with Microsoft's mail tools by decoding metadata and attachments encapsulated/embedded in a TNEF encoded attachment (aka winmail.dat).
Support: Thunderbird and SeaMonkey
→
A MutasdMeg! megnyitja és letölthetővé teszi a levelek TNEF (Transport Neutral Encapsulation Format – szállítási semleges befoglaló formátum) kódolással csatolt mellékleteit (általában winmail.dat).
Támogatás: Thunderbird és SeaMonkey

3. Image captions
Original TNEF file with extracted attachments
→
Eredeti TNEF (Transport Neutral Encapsulation Format – szállítási semleges befoglaló formátum) fájl kibontott mellékletekkel

**Comment by ovari** [comment]
Please refer to https://github.com/dugite-code/LookOut-fix-version/issues/23#issue-384232653 on GitHub as it has been edited. You may not have received an email with the latest update. Thank you

**Comment by dugite-code** [comment]
Thanks for the Translation Much appreciated.

I didn't change the title just yet as I kind of see it as the "brand name" of the addon. I guess it could be argued it's better to have a localised name for it but i'll give that so further thought later.

Just note the extended description is still in english. If you find some free time to look into it I'll be happy to update that as well.

```
Original LookOut add-on by Aron Rubin for Mozilla Thunderbird is abandoned September 30, 2011:
https://addons.mozilla.org/addon/lookout/

Does it mean its death? Of course not! It has been reborn! I brought it back to life!
Now it is called LookOut (fix version) and works with all new Thunderbird versions.

LookOut (fix version) - based on last version LookOut+ 1.2.15 by Attila K. Mergl (Last Updated: October 15, 2013)
https://addons.mozilla.org/addon/lookout-1/

Please before use, remove or disable the original LookOut and LookOut+ !

=====================
What is LookOut?

LookOut is a plugin which allows Thunderbird (and SeaMonkey) to interface with Microsoft's mail tools by decoding metadata and attachments encapsulated/embedded in a TNEF encoded attachment (aka winmail.dat). 
The TNEF decoding engine was inspired (with permission) by the TNEF project. LookOut has a full MAPI decoder and the ability to transcode some of those properties to iCalendar (ics) and vCard (vcf) formats. 
As an option all MAPI properties within a email can be viewed so other types of information can be deciphered.
```

**Comment by ovari** [comment]
Névjegyzék (CardBook)
https://addons.thunderbird.net/hu/thunderbird/addon/cardbook/

Tömörített fejléc (CompactHeader)
https://addons.thunderbird.net/hu/thunderbird/addon/compactheader/

Nyelvtan-ellenőrzés (Grammar Checker)
https://addons.thunderbird.net/hu/thunderbird/addon/grammar-checker/

Üzenet átirányítás (Mail Redirect)
https://addons.thunderbird.net/hu/thunderbird/addon/mailredirect/

Területi kapcsoló (Simple Locale Switcher)
https://addons.thunderbird.net/hu/thunderbird/addon/simple-locale-switcher/

Attila, the previous developer, call LookOut the name in Hungarian too.

**Comment by ovari** [comment]
Your file has it localized this way too at:
https://github.com/dugite-code/LookOut-fix-version/blob/master/src/install.rdf

**Comment by dugite-code** [comment]
@ovari fair enough, you're right. I've gone and changed the title as well
