### ISSUE TITLE
Save as Individual files not working

### ISSUE THREAD

**Issue by dugite-code** [dugite-code/LookOut-fix-version#7]
Right clicking a file and selecting Save as opens dialogue, Unfortunately the file is not saved

**Comment by dugite-code** [comment]
Note: current work-around is to double click to open then select Save File

**Comment by berlincount** [comment]
This doesn't do anything on MacOS X.

**Comment by dugite-code** [comment]
I've yet to publish changes from https://github.com/TB-throwback/LookOut-fix-version/pull/28 I believe these changes will fix your issue.

I'll try to publish it soon so it apears in the new year. You can just zip the src dir in non compression qnd rename to xpi if it's urgent
